{{- if and (include "player-fe.externalSecretsEnabled" . | trim) .Values.playerFe.secretManager.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.playerFe.secretManager.targetSecretName }}
  labels:
    {{- include "player-fe.playerFe.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.playerFe.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.playerFe.externalSecrets.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.playerFe.secretManager.targetSecretName }}
    creationPolicy: Owner
    template:
      data:
        {{ .Values.playerFe.secretManager.fileName }}: {{ `"{{ .env }}"` }}
  data:
    - secretKey: env
      remoteRef:
        key: {{ .Values.playerFe.secretManager.secretName }}
        version: {{ .Values.playerFe.secretManager.secretVersion | quote }}
{{- end }}
{{- if and (include "player-fe.externalSecretsEnabled" . | trim) .Values.ingress.tls.enabled .Values.ingress.tlsSecretName }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.ingress.tlsSecretName }}
  labels:
    {{- include "player-fe.playerFe.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.playerFe.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.playerFe.externalSecrets.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.ingress.tlsSecretName }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: {{ `"{{ .crt }}"` }}
        tls.key: {{ `"{{ .key }}"` }}
  data:
    - secretKey: crt
      remoteRef:
        key: {{ .Values.ingress.tls.certSecretName }}
        version: {{ .Values.ingress.tls.certSecretVersion | quote }}
    - secretKey: key
      remoteRef:
        key: {{ .Values.ingress.tls.keySecretName }}
        version: {{ .Values.ingress.tls.keySecretVersion | quote }}
{{- end }}
{{- if and (include "player-fe.externalSecretsEnabled" . | trim) .Values.playerFe.imagePullSecret.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.playerFe.imagePullSecret.targetSecretName }}
  labels:
    {{- include "player-fe.playerFe.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.playerFe.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.playerFe.externalSecrets.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.playerFe.imagePullSecret.targetSecretName }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: {{ `"{{ .dockerconfig }}"` }}
  data:
    - secretKey: dockerconfig
      remoteRef:
        key: {{ .Values.playerFe.imagePullSecret.secretName }}
        version: {{ .Values.playerFe.imagePullSecret.secretVersion | quote }}
{{- end }}
