{{- if and .Values.playerFe.enabled .Values.playerFe.ingress.enabled .Values.ingress.tlsExternalSecret.enabled .Values.ingress.tlsSecretName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.ingress.tlsSecretName }}
  labels:
    {{- include "player-fe.playerFe.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: {{ .Values.ingress.tlsExternalSecret.secretStoreRef.kind }}
    name: {{ .Values.ingress.tlsExternalSecret.secretStoreRef.name }}
  target:
    name: {{ .Values.ingress.tlsSecretName }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ `{{ .tlsCrt }}` }}"
        tls.key: "{{ `{{ .tlsKey }}` }}"
  data:
    - secretKey: tlsCrt
      remoteRef:
        key: {{ .Values.ingress.tlsExternalSecret.remoteRefs.tlsCrt.key }}
        version: {{ .Values.ingress.tlsExternalSecret.remoteRefs.tlsCrt.version | quote }}
    - secretKey: tlsKey
      remoteRef:
        key: {{ .Values.ingress.tlsExternalSecret.remoteRefs.tlsKey.key }}
        version: {{ .Values.ingress.tlsExternalSecret.remoteRefs.tlsKey.version | quote }}
{{- end }}
