{{- if and .Values.playerFe.enabled (include "player-fe.csiVolumeNeeded" . | trim) }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "player-fe.secretProviderClassName" . }}
  labels:
    {{- include "player-fe.playerFe.labels" . | nindent 4 }}
spec:
  provider: gke
  parameters:
    secrets: |
      {{- if .Values.playerFe.secretManager.enabled }}
      - resourceName: "projects/{{ .Values.playerFe.secretManager.projectNumber }}/secrets/{{ .Values.playerFe.secretManager.secretName }}/versions/{{ .Values.playerFe.secretManager.secretVersion }}"
        path: "{{ .Values.playerFe.secretManager.fileName }}"
      {{ end }}
      {{- if include "player-fe.csiTlsEnabled" . | trim }}
      - resourceName: "projects/{{ .Values.ingress.tls.projectNumber | default .Values.playerFe.secretManager.projectNumber }}/secrets/{{ .Values.ingress.tls.certSecretName }}/versions/{{ .Values.ingress.tls.certSecretVersion }}"
        path: "tls.crt"
      - resourceName: "projects/{{ .Values.ingress.tls.projectNumber | default .Values.playerFe.secretManager.projectNumber }}/secrets/{{ .Values.ingress.tls.keySecretName }}/versions/{{ .Values.ingress.tls.keySecretVersion }}"
        path: "tls.key"
      {{- end }}
{{- end }}
