{{- if .Values.playerFe.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-fe
  labels:
    {{- include "player-fe.playerFe.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.playerFe.replicaCount }}
  selector:
    matchLabels:
      app: player-fe
  template:
    metadata:
      labels:
        app: player-fe
    spec:
      {{- with .Values.playerFe.serviceAccountName }}
      serviceAccountName: {{ . }}
      {{- end }}
      {{- if include "player-fe.imagePullSecretEnabled" . | trim }}
      imagePullSecrets:
        - name: {{ .Values.playerFe.imagePullSecret.targetSecretName }}
      {{- end }}
      containers:
        - name: player-fe
          image: "{{ .Values.playerFe.image.repository }}:{{ .Values.playerFe.image.tag }}"
          imagePullPolicy: {{ .Values.playerFe.image.pullPolicy }}
          {{- with .Values.playerFe.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.playerFe.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.playerFe.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.playerFe.secretManager.enabled }}
          volumeMounts:
            - name: secret-manager
              mountPath: {{ .Values.playerFe.secretManager.mountPath }}
              subPath: {{ .Values.playerFe.secretManager.fileName }}
              readOnly: true
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.playerFe.service.port }}
      {{- if .Values.playerFe.secretManager.enabled }}
      volumes:
        - name: secret-manager
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "player-fe.secretProviderClassName" . | quote }}
      {{- end }}
{{- end }}
