{{- if include "player-fe.externalSecretsEnabled" . | trim }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.playerFe.externalSecrets.secretStoreName }}
  labels:
    {{- include "player-fe.playerFe.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ required "playerFe.externalSecrets.gcp.projectID is required" .Values.playerFe.externalSecrets.gcp.projectID | quote }}
      auth:
        workloadIdentity:
          clusterLocation: {{ required "playerFe.externalSecrets.gcp.clusterLocation is required" .Values.playerFe.externalSecrets.gcp.clusterLocation | quote }}
          clusterName: {{ required "playerFe.externalSecrets.gcp.clusterName is required" .Values.playerFe.externalSecrets.gcp.clusterName | quote }}
          serviceAccountRef:
            name: {{ default "default" .Values.playerFe.serviceAccountName | quote }}
{{- end }}
