{{- if and .Values.playerFe.enabled (include "player-fe.csiTlsEnabled" . | trim) }}
apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: {{ .Values.ingress.tlsSecretName }}
  labels:
    {{- include "player-fe.playerFe.labels" . | nindent 4 }}
spec:
  serviceAccountName: {{ default "default" .Values.ingress.tls.serviceAccountName | quote }}
  secretProviderClassName: {{ include "player-fe.secretProviderClassName" . | quote }}
  secretObject:
    type: kubernetes.io/tls
    data:
      - sourcePath: tls.crt
        targetKey: tls.crt
      - sourcePath: tls.key
        targetKey: tls.key
{{- end }}
