ingress:
  className: nginx
  host: player.my-cool.server
  tlsSecretName: "player-fe-secret-tls"
  tls:
    enabled: true
    certSecretName: player-fe-selfsigned-crt
    certSecretVersion: "1"
    keySecretName: player-fe-selfsigned-key
    keySecretVersion: "1"
  fe:
    annotations:
      kubernetes.io/ingress.class: nginx

playerFe:
  enabled: true
  replicaCount: 1
  serviceAccountName: "default"
  externalSecrets:
    enabled: true
    refreshInterval: 1h
    secretStoreName: player-fe-gcp-sm
    gcp:
      projectID: "pilot-nebent"
      clusterName: "qa-pilot-claster"
      clusterLocation: "europe-west3-a"
  image:
    repository: registry.nebent.net/base-images/base-nginx
    tag: "fbb5a591"
    pullPolicy: IfNotPresent
  secretManager:
    enabled: true
    secretName: my-secret-file
    secretVersion: "1"
    targetSecretName: player-fe-env
    mountPath: /app/.env
    fileName: env
  imagePullSecret:
    enabled: true
    secretName: docker-registry-at
    secretVersion: "1"
    targetSecretName: player-fe-image-pull
  service:
    type: ClusterIP
    port: 80
    annotations: {}
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1024Mi
  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 15
    periodSeconds: 20
  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 5
    periodSeconds: 10
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  ingress:
    enabled: true
    path: /
    pathType: Prefix
