ingress:
  className: nginx
  host: player.my-cool.server
  tlsSecretName: "player-fe-secret-tls"
  tls:
    csiSync: true
    secretProviderClassName: player-fe-csi
    serviceAccountName: "default"
    projectNumber: "119263735347"
    certSecretName: player-fe-selfsigned-crt
    certSecretVersion: 1
    keySecretName: player-fe-selfsigned-key
    keySecretVersion: 1
  fe:
    annotations:
      kubernetes.io/ingress.class: nginx

playerFe:
  enabled: true
  replicaCount: 1
  serviceAccountName: "default"
  image:
    repository: nginx
    tag: "1.27"
    pullPolicy: IfNotPresent
  secretManager:
    enabled: true
    secretProviderClassName: player-fe-secrets
    projectNumber: "119263735347"
    secretName: my-secret-file
    secretVersion: 1
    mountPath: /app/.env
    fileName: env
  service:
    type: ClusterIP
    port: 80
    annotations: {}
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1024Mi
  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 15
    periodSeconds: 20
  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 5
    periodSeconds: 10
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  ingress:
    enabled: true
    path: /
    pathType: Prefix
